// Mock data for development without database connection
// Source: larmorbaden.com (site officiel) + données touristiques locales
// Photos: Wikimedia Commons (CC BY-SA 3.0 / CC0) — vraies photos de Larmor-Baden et du Golfe du Morbihan

export const mockPois = [
  {
    id: "1",
    name: "Port de Larmor-Baden",
    slug: "port-larmor-baden",
    type: "port",
    summary: "Port de pêche et de plaisance, embarquement vers Gavrinis et les îles du Golfe",
    content: "Le port de Larmor-Baden est le cœur battant de la commune. Port de pêche traditionnel et de plaisance, c'est le point de départ des navettes vers l'île de Gavrinis et son cairn mégalithique classé Monument Historique. La capitainerie propose des services aux plaisanciers (eau, électricité, sanitaires). À marée basse, le paysage se transforme et révèle l'estran rocheux caractéristique du Golfe. Le port accueille également la Semaine du Golfe, événement maritime majeur qui rassemble des centaines de voiliers traditionnels.",
    lat: 47.5835,
    lng: -2.8957,
    tags: ["port", "capitainerie", "Gavrinis", "Semaine du Golfe", "plaisance"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 60,
    priceLevel: 0,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Port_de_Larmor-Baden.jpg/1280px-Port_de_Larmor-Baden.jpg",
    address: "Port de Larmor-Baden, 56870 Larmor-Baden",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Île aux Moines",
    slug: "ile-aux-moines",
    type: "ile",
    summary: "La perle du Golfe du Morbihan, plus grande île avec ses plages et hortensias",
    content: "L'Île aux Moines est la plus grande île du Golfe du Morbihan. En forme de croix, elle offre 7 km de long pour seulement 3,5 km de large. Ses plages de sable fin, ses sentiers côtiers bordés d'hortensias et son village pittoresque aux maisons de pêcheurs en font la destination incontournable du Golfe. Accessible en 5 minutes depuis l'embarcadère de Port-Blanc à Baden, elle se découvre idéalement à pied ou à vélo. Ne manquez pas le dolmen de Penhap, la pointe du Trec'h et le Bois d'Amour.",
    lat: 47.5890,
    lng: -2.8510,
    tags: ["ile", "plage", "village", "velo", "dolmen"],
    season: ["printemps", "ete", "automne"],
    kidFriendly: true,
    durationMin: 240,
    priceLevel: 1,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Plage_du_Gored-%C3%8Ele-aux-Moines_%281%29.jpg/1280px-Plage_du_Gored-%C3%8Ele-aux-Moines_%281%29.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Cairn de Gavrinis",
    slug: "cairn-gavrinis",
    type: "patrimoine",
    summary: "Joyau mégalithique classé, gravures néolithiques vieilles de 6 000 ans",
    content: "Le cairn de Gavrinis, sur l'île du même nom accessible uniquement depuis le port de Larmor-Baden, est l'un des plus beaux monuments mégalithiques d'Europe. Classé Monument Historique, il date de 3500 avant J.-C. Ses 29 dalles intérieures sont ornées de gravures néolithiques d'une finesse remarquable représentant des haches, des arcs et des motifs géométriques. La visite guidée (obligatoire) dure environ 1h15, traversée en bateau comprise. Réservation fortement conseillée en saison. Ouvert d'avril à octobre.",
    lat: 47.5710,
    lng: -2.8920,
    tags: ["megalithes", "Monument Historique", "neolithique", "visite guidee"],
    season: ["printemps", "ete", "automne"],
    kidFriendly: true,
    durationMin: 120,
    priceLevel: 2,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cairn_Gavrinis_entrance.jpg/1280px-Cairn_Gavrinis_entrance.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Île Berder",
    slug: "ile-berder",
    type: "ile",
    summary: "Île accessible à pied à marée basse par un passage submersible unique",
    content: "L'île Berder est un joyau naturel accessible à pied depuis Larmor-Baden grâce à un passage submersible praticable à marée basse. D'une superficie de 23 hectares, elle offre un sentier de tour d'île de 3 km à travers une végétation luxuriante de pins maritimes, chênes verts et mimosas. Attention : il est impératif de vérifier les horaires de marées sur maree.secretsmaree.com avant de s'y rendre. Le passage est submergé environ 4 heures par cycle de marée. Les horaires de passage sont affichés à l'entrée et disponibles en mairie.",
    lat: 47.5810,
    lng: -2.8880,
    tags: ["ile", "maree", "nature", "sentier", "passage submersible"],
    season: ["printemps", "ete", "automne"],
    kidFriendly: true,
    durationMin: 120,
    priceLevel: 0,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/%C3%8Ele_de_Berder-V%C3%A9g%C3%A9tation.jpg/1280px-%C3%8Ele_de_Berder-V%C3%A9g%C3%A9tation.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Pen en Toul",
    slug: "pen-en-toul",
    type: "patrimoine",
    summary: "Marais protégé entre Larmor-Baden et Baden, digue historique et chantiers nature",
    content: "Pen en Toul est un site naturel remarquable situé au nord de Larmor-Baden, entre la commune et Baden. Cet ancien marais salant est protégé par le Conservatoire du Littoral depuis 2000 et géré par Bretagne Vivante. Un sentier de découverte de 3,3 km permet l'observation des oiseaux marins dans un cadre préservé (bois, landes, bocages, prairies humides). Le site fait l'objet de chantiers nature réguliers pour préserver sa biodiversité exceptionnelle. Se renseigner en mairie.",
    lat: 47.5929,
    lng: -2.8909,
    tags: ["nature", "panorama", "biodiversite", "oiseaux", "digue"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 90,
    priceLevel: 0,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Marais_de_Pen_an_Toul.jpg/1280px-Marais_de_Pen_an_Toul.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "Plage de Berchis",
    slug: "plage-berchis",
    type: "plage",
    summary: "Plage familiale face à l'île de Radenec dans le Golfe du Morbihan",
    content: "La plage de Berchis offre un panorama exceptionnel sur le Golfe du Morbihan et l'île de Radenec. Cette plage de sable et de rochers bénéficie d'une excellente qualité d'eau (3 étoiles). Idéale pour la baignade en été et les promenades contemplatives le reste de l'année. Le sentier côtier GR34 passe juste au-dessus, permettant de combiner randonnée et baignade.",
    lat: 47.5823,
    lng: -2.9061,
    tags: ["plage", "baignade", "famille", "GR34"],
    season: ["ete"],
    kidFriendly: true,
    durationMin: 180,
    priceLevel: 0,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg/1280px-Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "Sentier côtier GR34",
    slug: "sentier-cotier-gr34",
    type: "randonnee",
    summary: "Le mythique sentier des douaniers le long du Golfe du Morbihan",
    content: "Le GR34, célèbre sentier des douaniers, longe la côte de Larmor-Baden en offrant des panoramas spectaculaires sur le Golfe du Morbihan et ses 42 îles. Le tronçon de Larmor-Baden traverse des paysages variés : landes, pins maritimes, rochers de granit et criques secrètes. Il relie le port de Larmor-Baden à Baden en passant par la Pointe de Berchis et Pen en Toul. Balisage blanc et rouge. Accessible toute l'année.",
    lat: 47.5840,
    lng: -2.8980,
    tags: ["randonnee", "GR34", "sentier des douaniers", "panorama"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 90,
    priceLevel: 0,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Port_de_Larmor-Baden.jpg/1280px-Port_de_Larmor-Baden.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "Marché de Larmor-Baden",
    slug: "marche-larmor-baden",
    type: "marche",
    summary: "Marché traditionnel le jeudi matin + marchés nocturnes estivaux",
    content: "Chaque jeudi matin, le marché de Larmor-Baden rassemble producteurs locaux et artisans sur la place de l'église. Huîtres du Golfe, crêpes, cidre breton, légumes du pays vannetais, poissons frais... Une immersion dans les saveurs authentiques de la Bretagne Sud. En été, des marchés nocturnes festifs sont organisés avec animations musicales, dégustations et artisanat local. Renseignements à la mairie : 02 97 57 05 38.",
    lat: 47.5850,
    lng: -2.8955,
    tags: ["marche", "produits locaux", "huitres", "marche nocturne", "artisanat"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 60,
    priceLevel: 1,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg/1280px-Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    name: "Embarcadère de Port-Blanc",
    slug: "embarcadere-port-blanc",
    type: "port",
    summary: "Embarquement pour l'Île aux Moines, traversée en 5 minutes",
    content: "L'embarcadère de Port-Blanc à Baden est le point de départ principal pour rejoindre l'Île aux Moines. La traversée ne dure que 5 minutes et offre déjà une vue magnifique sur le Golfe. Des navettes fonctionnent toute l'année avec une fréquence renforcée en été. Grand parking gratuit à proximité. C'est aussi le point de départ de croisières commentées dans le Golfe du Morbihan.",
    lat: 47.6030,
    lng: -2.8600,
    tags: ["port", "traversee", "Ile aux Moines", "parking"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 30,
    priceLevel: 1,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Port_de_Larmor-Baden.jpg/1280px-Port_de_Larmor-Baden.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    name: "Salle Le Cairn",
    slug: "salle-le-cairn",
    type: "patrimoine",
    summary: "Espace culturel communal : spectacles, concerts et événements « Larmor Côté Scène »",
    content: "La Salle Le Cairn est l'espace culturel de Larmor-Baden. Elle accueille la programmation « Larmor Côté Scène » avec des spectacles vivants, concerts, pièces de théâtre et événements tout au long de l'année. La salle est également disponible à la location pour des événements privés. Consultez la programmation et les tarifs sur le site officiel de la commune larmorbaden.com. Parking à proximité.",
    lat: 47.5855,
    lng: -2.8948,
    tags: ["culture", "spectacles", "concerts", "Larmor Cote Scene"],
    season: ["printemps", "ete", "automne", "hiver"],
    kidFriendly: true,
    durationMin: 120,
    priceLevel: 1,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cairn_Gavrinis_entrance.jpg/1280px-Cairn_Gavrinis_entrance.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    name: "École de voile",
    slug: "ecole-de-voile",
    type: "activite",
    summary: "Activités nautiques : voile, kayak, paddle dans le Golfe du Morbihan",
    content: "L'école de voile de Larmor-Baden propose des cours et locations de voiliers, dériveurs, kayaks et paddle dans le cadre exceptionnel du Golfe du Morbihan. Stages pour enfants et adultes, du débutant au confirmé. Le plan d'eau protégé du Golfe est idéal pour l'apprentissage. L'école participe également aux animations de la Semaine du Golfe, grand rassemblement de voiliers traditionnels.",
    lat: 47.5830,
    lng: -2.8960,
    tags: ["nautisme", "voile", "kayak", "paddle", "Semaine du Golfe"],
    season: ["printemps", "ete", "automne"],
    kidFriendly: true,
    durationMin: 120,
    priceLevel: 2,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg/1280px-Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockHikes = [
  {
    id: "1",
    name: "Tour de l'Île aux Moines",
    slug: "tour-ile-aux-moines",
    description: "Randonnée complète autour de l'Île aux Moines, la perle du Golfe. Accessible depuis l'embarcadère de Port-Blanc à Baden (traversée 5 min). Découvrez ses plages de sable fin, criques secrètes, dolmens et points de vue exceptionnels sur le Golfe du Morbihan.",
    distanceKm: 12.5,
    durationMin: 180,
    difficulty: "facile",
    type: "boucle",
    startPoint: "Embarcadère de l'Île aux Moines (Port-Blanc, Baden)",
    highlights: ["Plage de Brouel", "Pointe du Trec'h", "Bois d'Amour", "Port du Lério", "Dolmen de Penhap"],
    equipment: ["Chaussures de marche", "Eau", "Crème solaire"],
    bestSeason: "Printemps et automne pour éviter la foule estivale",
    warnings: ["Vérifier les horaires de bateau (dernière navette ~19h en été)", "Prévoir le retour"],
    facilities: ["Restaurants", "Toilettes", "Commerces", "Location de vélos"],
    tags: ["ile", "panorama", "plages", "dolmen"],
    kidFriendly: true,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Plage_du_Gored-%C3%8Ele-aux-Moines_%281%29.jpg/1280px-Plage_du_Gored-%C3%8Ele-aux-Moines_%281%29.jpg",
    elevationGain: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Sentier côtier Larmor-Baden (GR34)",
    slug: "sentier-cotier-larmor-baden",
    description: "Tronçon du mythique GR34 (sentier des douaniers) le long du Golfe du Morbihan. De Larmor-Baden à Baden, entre pins maritimes, landes et rochers de granit. Vues imprenables sur Gavrinis, Er Lannic et les îles du Golfe. Mentionné parmi les sentiers côtiers sur larmorbaden.com.",
    distanceKm: 8.0,
    durationMin: 150,
    difficulty: "facile",
    type: "aller-retour",
    startPoint: "Port de Larmor-Baden",
    highlights: ["Port de Larmor-Baden", "Pointe de Berchis", "Vue sur Gavrinis et Er Lannic", "Baden"],
    equipment: ["Chaussures de marche", "Jumelles recommandées", "Eau"],
    bestSeason: "Toute l'année, magnifique au coucher du soleil",
    warnings: ["Sentier parfois étroit", "Balisage blanc et rouge GR34"],
    facilities: ["Parking au port", "Restaurants au port et à Baden"],
    tags: ["cotier", "GR34", "panorama", "accessible"],
    kidFriendly: true,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Port_de_Larmor-Baden.jpg/1280px-Port_de_Larmor-Baden.jpg",
    elevationGain: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Tour de l'Île Berder",
    slug: "tour-ile-berder",
    description: "Boucle de 3 km autour de l'île Berder, accessible à pied depuis Larmor-Baden à marée basse par un passage submersible. Pins maritimes, chênes verts et mimosas dans un cadre sauvage. L'île Berder est l'un des sites phares référencés sur le site officiel de la commune.",
    distanceKm: 3.0,
    durationMin: 60,
    difficulty: "facile",
    type: "boucle",
    startPoint: "Passage submersible vers l'île Berder, Larmor-Baden",
    highlights: ["Passage submersible", "Tour de l'île", "Vue sur le Golfe", "Végétation méditerranéenne"],
    equipment: ["Chaussures de marche", "Appareil photo"],
    bestSeason: "Printemps (mimosas en fleur) et été",
    warnings: ["IMPÉRATIF : vérifier les horaires de marées sur maree.secretsmaree.com !", "Passage submergé ~4h par cycle", "Horaires affichés à l'entrée et disponibles en mairie (02 97 57 05 38)"],
    facilities: ["Parking gratuit côté continent"],
    tags: ["ile", "maree", "nature", "facile"],
    kidFriendly: true,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/%C3%8Ele_de_Berder-V%C3%A9g%C3%A9tation.jpg/1280px-%C3%8Ele_de_Berder-V%C3%A9g%C3%A9tation.jpg",
    elevationGain: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Boucle de Pen en Toul",
    slug: "boucle-pen-en-toul",
    description: "Promenade jusqu'au site naturel de Pen en Toul, relié au continent par une digue. Vue panoramique à 360° sur le Golfe du Morbihan, l'île de Gavrinis et l'entrée du Golfe. Site mentionné comme lieu de chantiers nature sur larmorbaden.com.",
    distanceKm: 4.5,
    durationMin: 75,
    difficulty: "facile",
    type: "boucle",
    startPoint: "Parking de Pen en Toul, Larmor-Baden",
    highlights: ["Digue de Pen en Toul", "Panorama 360°", "Vue sur Gavrinis", "Observation oiseaux marins"],
    equipment: ["Jumelles", "Chaussures de marche", "Coupe-vent"],
    bestSeason: "Toute l'année — superbe en hiver pour l'observation des oiseaux",
    warnings: ["Restrictions de circulation possibles sur la digue (travaux de sécurisation)", "Se renseigner en mairie"],
    facilities: ["Parking"],
    tags: ["nature", "panorama", "oiseaux", "accessible"],
    kidFriendly: true,
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Marais_de_Pen_an_Toul.jpg/1280px-Marais_de_Pen_an_Toul.jpg",
    elevationGain: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockItineraries = [
  {
    id: "1",
    name: "Week-end découverte du Golfe",
    slug: "weekend-decouverte-golfe",
    description: "Un week-end parfait pour découvrir les essentiels de Larmor-Baden : traversée vers le Cairn de Gavrinis (monument mégalithique classé), Île aux Moines depuis Port-Blanc, sentier côtier GR34 et gastronomie locale au marché du jeudi.",
    days: 2,
    blocks: [
      {
        day: 1,
        morning: { activity: "Visite guidée du Cairn de Gavrinis (traversée depuis le port de Larmor-Baden)", duration: 120 },
        lunch: { activity: "Déjeuner au port de Larmor-Baden — huîtres du Golfe", duration: 90 },
        afternoon: { activity: "Traversée vers l'Île aux Moines depuis Port-Blanc (5 min) et tour de l'île", duration: 180 },
        evening: { activity: "Dîner crêperie bretonne", duration: 90 },
      },
      {
        day: 2,
        morning: { activity: "Randonnée GR34 sentier côtier + Pointe de Berchis", duration: 150 },
        lunch: { activity: "Pique-nique à la Pointe de Berchis, vue sur le Golfe", duration: 60 },
        afternoon: { activity: "Tour de l'île Berder à marée basse (vérifier horaires !)", duration: 90 },
        evening: { activity: "Coucher de soleil depuis Pen en Toul", duration: 60 },
      },
    ],
    tags: ["weekend", "Gavrinis", "Ile aux Moines", "GR34"],
    profile: ["couple", "famille"],
    budget: "moyen",
    mobility: ["voiture"],
    interests: ["patrimoine", "nature", "gastronomie"],
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cairn_Gavrinis_entrance.jpg/1280px-Cairn_Gavrinis_entrance.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Semaine en famille au Golfe",
    slug: "semaine-famille",
    description: "Une semaine complète pour profiter de Larmor-Baden et du Golfe en famille : plages de Berchis, île Berder à marée basse, Cairn de Gavrinis, école de voile, marchés nocturnes estivaux et spectacles à la Salle Le Cairn (programmation Larmor Côté Scène).",
    days: 7,
    blocks: [],
    tags: ["semaine", "famille", "Ile Berder", "ecole de voile", "Cairn"],
    profile: ["famille"],
    budget: "moyen",
    mobility: ["voiture"],
    interests: ["plage", "nature", "enfants", "nautisme"],
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg/1280px-Le_golfe_du_morbihan_vu_du_port_de_larmor_baden_-_panoramio.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Escapade romantique au Morbihan",
    slug: "escapade-romantique",
    description: "Trois jours romantiques à Larmor-Baden : coucher de soleil depuis Pen en Toul, dîner gastronomique au port, traversée vers l'Île aux Moines, balade sur le sentier côtier GR34 et visite du Cairn de Gavrinis.",
    days: 3,
    blocks: [],
    tags: ["romantique", "Pen en Toul", "Gavrinis", "gastronomie"],
    profile: ["couple"],
    budget: "eleve",
    mobility: ["voiture"],
    interests: ["gastronomie", "panorama", "detente", "patrimoine"],
    published: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Port_de_Larmor-Baden.jpg/1280px-Port_de_Larmor-Baden.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockStats = {
  pois: 42,
  hikes: 15,
  itineraries: 12,
};

/* ─────────────────────────────────────────────────────
   Informations pratiques — source : larmorbaden.com
   ───────────────────────────────────────────────────── */
export const communeInfo = {
  name: "Larmor-Baden",
  postalCode: "56870",
  departement: "Morbihan",
  region: "Bretagne",
  mairie: {
    address: "2 Place de l'église, 56870 Larmor-Baden",
    phone: "02 97 57 05 38",
    website: "https://www.larmorbaden.com",
    hours: [
      { day: "Mardi", time: "9h00 – 12h00" },
      { day: "Mercredi", time: "9h00 – 12h00" },
      { day: "Jeudi", time: "9h00 – 12h00" },
      { day: "Vendredi", time: "9h00 – 12h00 / 14h00 – 16h30" },
      { day: "Samedi", time: "9h00 – 12h00" },
    ],
  },
  agencePostale: {
    hours: "Mardi au samedi de 9h à 12h",
  },
  sitesTouristiques: [
    "Île Berder — accessible à pied à marée basse",
    "Île de Gavrinis — cairn mégalithique classé",
    "Pen en Toul — site naturel protégé",
    "Sentiers côtiers GR34",
  ],
  hebergements: [
    "Hôtels",
    "Campings",
    "Chambres d'hôtes",
    "Locations de vacances",
    "Résidence de vacances",
  ],
  evenements: [
    "Semaine du Golfe — rassemblement de voiliers traditionnels",
    "Marchés nocturnes estivaux",
    "Programmation Larmor Côté Scène (Salle Le Cairn)",
  ],
  liensUtiles: {
    siteOfficiel: "https://www.larmorbaden.com",
    horairesMarees: "https://maree.secretsmaree.com",
    port: "https://www.larmorbaden.com/port-mouillage/la-vie-du-port/presentation-de-l-equipe",
    officeTourisme: "https://www.larmorbaden.com/tourisme-decouverte/pratique/information-tourisme.html",
  },
};